[build]
  publish = "dist"
  command = "npm run build"

# Prerender pages for SEO
[[plugins]]
  package = "@netlify/plugin-sitemap"

[build.environment]
  NETLIFY_USE_PRERENDER = "true"

# Configurações para HTTP/2 e compressão
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Configurações de cache para recursos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Configurações de redirecionamento
[[redirects]]
  from = "/vehicle-finance"
  to = "/simulador-financiamento-veiculos"
  status = 301
  force = true

[[redirects]]
  from = "/financiamento-veiculo"
  to = "/simulador-financiamento-veiculos"
  status = 301
  force = true

[[redirects]]
  from = "/simulador-da-caixa"
  to = "/simulador-caixa-financiamento"
  status = 301
  force = true

[[redirects]]
  from = "/caixa-simulador-financiamento"
  to = "/simulador-caixa-financiamento"
  status = 301
  force = true

[[redirects]]
  from = "/financiamento-parcela-balao"
  to = "/simulador-parcela-balao"
  status = 301
  force = true

[[redirects]]
  from = "/financiamento-vfg"
  to = "/simulador-parcela-balao"
  status = 301
  force = true

[[redirects]]
  from = "/financiamento-caminhoes"
  to = "/financiamento-caminhao"
  status = 301
  force = true

[[redirects]]
  from = "/financiamento-motos"
  to = "/financiamento-moto"
  status = 301
  force = true

[[redirects]]
  from = "/simulador-financiamento"
  to = "/simulador-de-financiamento"
  status = 301
  force = true

[[redirects]]
  from = "/calculadora-financiamento"
  to = "/simulador-de-financiamento"
  status = 301
  force = true

# Configuração para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200